theme: jekyll-theme-hacker
title: Martin Kong's Homesite
description: Personal Website of Martin Kong@OSU - research group and interests, publications, software and service.
github:
  is_project_page: false
